project: 
  type: website
  
website: 
  page-navigation: true
  title: "Barefoot Ocean Partner Manual" 
  site-url: "https://barefoot-ocean.github.io/Partner-Manual/" 
  repo-url: https://github.com/Barefoot-Ocean/Partner-Manual
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Barefoot Ocean, 2024"
    
  sidebar:
    logo: "images/bfo_logo.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://barefootocean.org/
        text: "Barefoot Ocean Website"
      - icon: linkedin
        href: https://www.linkedin.com/search/results/all/?fetchDeterministicClustersOnly=true&heroEntityKey=urn%3Ali%3Aorganization%3A89840617&keywords=barefoot%20ocean&origin=RICH_QUERY_SUGGESTION&position=0&searchId=eec6c7fe-7db0-4233-9c69-543232e40271&sid=DWx&spellCorrectionEnabled=false
        text: "Barefoot Ocean LinkedIn"     
      - icon: github
        href: https://github.com/openscapes/quarto-website-tutorial
        text: "Github"
      - icon: check-circle-fill
        href: https://dynamicview.smartsheet.com/
        text: "Smartsheet Dynamic View"  
      - icon: bar-chart-fill
        href: https://barefootocean.shinyapps.io/fisheries_dashboard/_w_ab83fe1c/_w_86d66a5f/_w_88f8a599/?page=sign_in
        text: "Community Fisheries Dashboard"
      - icon: house-fill
        href: https://barefootocean.shinyapps.io/hhsdashboard-dev/
        text: "Household Survey Dashboard"
        

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home - Languages
      - section: pages/index/index_en.qmd
        contents: 
          - pages/quick_guide/quick_guide_en.qmd
          - pages/full_guide/full_guide_en.qmd
          - pages/kobo_setup/kobo_setup_en.qmd
          - pages/smartsheet_intro/smartsheet_intro_en.qmd
          - pages/reference_files/reference_files_en.qmd
          - pages/data_validation/data_validation_en.qmd
          - pages/fisheries_dashboard/fisheries_dashboard_en.qmd
          - pages/socioeco_dashboard/socioeco_dashboard_en.qmd
      - section: pages/index/index_id.qmd
        contents: 
          - pages/quick_guide/quick_guide_id.qmd
          - pages/full_guide/full_guide_id.qmd
          - pages/kobo_setup/kobo_setup_id.qmd
          - pages/reference_files/reference_files_id.qmd
          - pages/data_validation/data_validation_id.qmd
      - section: pages/index/index_ceb.qmd
        contents:
          - pages/quick_guide/quick_guide_ceb.qmd
          - pages/full_guide/full_guide_ceb.qmd
          - pages/kobo_setup/kobo_setup_ceb.qmd
          - pages/reference_files/reference_files_ceb.qmd
          - pages/data_validation/data_validation_ceb.qmd
      - section: pages/index/index_fil.qmd
        contents:
          - pages/quick_guide/quick_guide_fil.qmd
          - pages/full_guide/full_guide_fil.qmd
          - pages/kobo_setup/kobo_setup_fil.qmd
          - pages/reference_files/reference_files_fil.qmd
          - pages/data_validation/data_validation_fil.qmd
      - section: pages/index/index_mg.qmd
        contents:
          - pages/quick_guide/quick_guide_mg.qmd
          - pages/full_guide/full_guide_mg.qmd
          - pages/kobo_setup/kobo_setup_mg.qmd
          - pages/reference_files/reference_files_mg.qmd
          - pages/data_validation/data_validation_mg.qmd
      - section: pages/index/index_fr.qmd
        contents:
          - pages/quick_guide/quick_guide_fr.qmd
          - pages/full_guide/full_guide_fr.qmd
          - pages/kobo_setup/kobo_setup_fr.qmd
          - pages/reference_files/reference_files_fr.qmd
          - pages/data_validation/data_validation_fr.qmd
      - section: pages/index/index_es.qmd
        contents:
          - pages/quick_guide/quick_guide_es.qmd
          - pages/full_guide/full_guide_es.qmd
          - pages/kobo_setup/kobo_setup_es.qmd
          - pages/reference_files/reference_files_es.qmd
          - pages/data_validation/data_validation_es.qmd
      - section: pages/index/index_pt.qmd
        contents:
          - pages/quick_guide/quick_guide_pt.qmd
          - pages/full_guide/full_guide_pt.qmd
          - pages/kobo_setup/kobo_setup_pt.qmd
          - pages/reference_files/reference_files_pt.qmd
          - pages/data_validation/data_validation_pt.qmd
      - section: pages/index/index_sw.qmd
        contents:
          - pages/quick_guide/quick_guide_sw.qmd
          - pages/full_guide/full_guide_sw.qmd
          - pages/kobo_setup/kobo_setup_sw.qmd
          - pages/reference_files/reference_files_sw.qmd
          - pages/data_validation/data_validation_sw.qmd
      - section: pages/index/index_tet.qmd




format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
    code-copy: true
    code-overflow: wrap
    toc: false


filters:
  - include-files.lua
  - quarto

  
