project: 
  type: website
  
website: 
  page-navigation: true
  title: "Barefoot Ocean Partner Manual" 
  site-url: "https://barefoot-ocean.github.io/Partner-Manual/" 
  repo-url: https://github.com/Barefoot-Ocean/Partner-Manual
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Blue Ventures, 2024"
    
  sidebar:
    logo: "images/bv_logo.png"
    background: "#25AADD"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://blueventures.org/
        text: "Blue Ventures Website"
      - icon: linkedin
        href: https://www.linkedin.com/company/blue-ventures
        text: "Blue Ventures LinkedIn"     
      - icon: github
        href: https://github.com/
        text: "Github"
      - icon: check-circle-fill
        href: https://dynamicview.smartsheet.com/
        text: "Smartsheet Dynamic View"  
      - icon: bar-chart-fill
        href: https://barefootocean.shinyapps.io/fisheries_dashboard/
        text: "Community Fisheries Data Dashboard"
      - icon: house-fill
        href: https://barefootocean.shinyapps.io/hhsdashboard-dev/
        text: "Social and Economic Dashboard"
        

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - section: pages/index/index_en.qmd
        contents: 
          - pages/quick_guide/quick_guide_en.qmd
          - pages/full_guide/full_guide_en.qmd
          - pages/kobo_setup/kobo_setup_en.qmd
          - pages/data_collection/data_collection_en.qmd
          - pages/landings_monitoring/landings_monitoring_en.qmd
          - pages/landings_profiling/landings_profiling_en.qmd
          - pages/reference_files/reference_files_en.qmd
          - pages/data_validation/data_validation_en.qmd
          - pages/fisheries_dashboard/fisheries_dashboard_en.qmd
          - pages/household_survey/household_survey_en.qmd
      - section: pages/index/index_id.qmd
        contents: 
          - pages/quick_guide/quick_guide_id.qmd
          - pages/full_guide/full_guide_id.qmd
          - pages/kobo_setup/kobo_setup_id.qmd
          - pages/data_collection/data_collection_id.qmd
          - pages/landings_monitoring/landings_monitoring_id.qmd
          - pages/landings_profiling/landings_profiling_id.qmd
          - pages/reference_files/reference_files_id.qmd
          - pages/data_validation/data_validation_id.qmd
          - pages/fisheries_dashboard/fisheries_dashboard_id.qmd
      - section: pages/index/index_ceb.qmd
        contents:
          - pages/quick_guide/quick_guide_ceb.qmd
          - pages/full_guide/full_guide_ceb.qmd
          - pages/kobo_setup/kobo_setup_ceb.qmd
          - pages/landings_monitoring/landings_monitoring_ceb.qmd
          - pages/landings_profiling/landings_profiling_ceb.qmd
          - pages/reference_files/reference_files_ceb.qmd
          - pages/data_validation/data_validation_ceb.qmd
          - pages/fisheries_dashboard/fisheries_dashboard_ceb.qmd
      - section: pages/index/index_fil.qmd
        contents:
          - pages/quick_guide/quick_guide_fil.qmd
          - pages/full_guide/full_guide_fil.qmd
          - pages/kobo_setup/kobo_setup_fil.qmd
          - pages/landings_monitoring/landings_monitoring_fil.qmd
          - pages/landings_profiling/landings_profiling_fil.qmd
          - pages/reference_files/reference_files_fil.qmd
          - pages/data_validation/data_validation_fil.qmd
          - pages/fisheries_dashboard/fisheries_dashboard_fil.qmd
      - section: pages/index/index_mg.qmd
        contents:
          - pages/quick_guide/quick_guide_mg.qmd
          - pages/full_guide/full_guide_mg.qmd
          - pages/kobo_setup/kobo_setup_mg.qmd
          - pages/landings_monitoring/landings_monitoring_mg.qmd
          - pages/landings_profiling/landings_profiling_mg.qmd
          - pages/reference_files/reference_files_mg.qmd
          - pages/data_validation/data_validation_mg.qmd
          - pages/fisheries_dashboard/fisheries_dashboard_mg.qmd
      - section: pages/index/index_fr.qmd
        contents:
          - pages/quick_guide/quick_guide_fr.qmd
          - pages/full_guide/full_guide_fr.qmd
          - pages/kobo_setup/kobo_setup_fr.qmd
          - pages/landings_monitoring/landings_monitoring_fr.qmd
          - pages/landings_profiling/landings_profiling_fr.qmd
          - pages/reference_files/reference_files_fr.qmd
          - pages/data_validation/data_validation_fr.qmd
          - pages/fisheries_dashboard/fisheries_dashboard_fr.qmd
      - section: pages/index/index_es.qmd
        contents:
          - pages/quick_guide/quick_guide_es.qmd
          - pages/full_guide/full_guide_es.qmd
          - pages/kobo_setup/kobo_setup_es.qmd
          - pages/landings_monitoring/landings_monitoring_es.qmd
          - pages/landings_profiling/landings_profiling_es.qmd
          - pages/reference_files/reference_files_es.qmd
          - pages/data_validation/data_validation_es.qmd
          - pages/fisheries_dashboard/fisheries_dashboard_es.qmd
      - section: pages/index/index_pt.qmd
        contents:
          - pages/quick_guide/quick_guide_pt.qmd
          - pages/full_guide/full_guide_pt.qmd
          - pages/kobo_setup/kobo_setup_pt.qmd
          - pages/landings_monitoring/landings_monitoring_pt.qmd
          - pages/landings_profiling/landings_profiling_pt.qmd
          - pages/reference_files/reference_files_pt.qmd
          - pages/data_validation/data_validation_pt.qmd
          - pages/fisheries_dashboard/fisheries_dashboard_pt.qmd
      - section: pages/index/index_sw.qmd
        contents:
          - pages/quick_guide/quick_guide_sw.qmd
          - pages/full_guide/full_guide_sw.qmd
          - pages/kobo_setup/kobo_setup_sw.qmd
          - pages/landings_monitoring/landings_monitoring_sw.qmd
          - pages/landings_profiling/landings_profiling_sw.qmd
          - pages/reference_files/reference_files_sw.qmd
          - pages/data_validation/data_validation_sw.qmd
          - pages/fisheries_dashboard/fisheries_dashboard_sw.qmd
      - section: pages/index/index_tet.qmd
        contents:
          - pages/quick_guide/quick_guide_tet.qmd
          - pages/full_guide/full_guide_tet.qmd
          - pages/kobo_setup/kobo_setup_tet.qmd
          - pages/landings_monitoring/landings_monitoring_tet.qmd
          - pages/landings_profiling/landings_profiling_tet.qmd
          - pages/reference_files/reference_files_tet.qmd
          - pages/data_validation/data_validation_tet.qmd
          - pages/fisheries_dashboard/fisheries_dashboard_tet.qmd




format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
    code-copy: true
    code-overflow: wrap
    toc: false


filters:
  - include-files.lua
  - quarto

  
