---
title: Household Survey
---

Introduction

The following household survey instrument captures socioeconomic and community perception data that can be used to establish essential social baselines and provide evidence of positive social outcomes following project activities focused on strengthening resource management. Survey questions were designed to understand and evaluate community response to project activities. These questions inform key indicators measuring change in livelihoods, fishing activities, financial resilience, knowledge of fishing regulations, attitude toward fisheries management, participation in fisheries management, gender equity, and trust in the community and leaders. The survey tool can yield results that underscore requirements for and contribute to the development of supplementary evaluations linked to project impacts, including aspects such as nutrition and gender equality

The survey primarily uses 5-point Likert scale, multiple choice, and binary questions to expedite data collection and analysis. The survey will be administered using a Kobo Toolbox form accessed through the KoboCollect app. The Kobo form can be completed on a mobile phone or tablet to expedite the survey process. 

Sampling Design 

Sampling is the procedure through which a subset of a population is chosen to accurately portray an overall population within an area of interest. The area of interest refers to a specific geographic region chosen for the purpose of measuring and assessing changes. Various techniques exist for selecting a sample, with one of the most time- and cost-efficient being cluster sampling. Cluster sampling is appropriate when a list of all households in a population is not available. In cluster sampling a population is divided into smaller groups or clusters and the households within these clusters form the sample. For each area of interest, the survey should aim to collect at least 100 complete responses. The larger the sample, the greater confidence is that the responses are representative of the community. In addition, a larger sample size allows for a smaller minimum detectable effect (MDE) size. For example, a sample size of approximately 100 households results in a minimum detectable effect (MDE) size of 25% at power of 90%. This means that with a sample size of 100 we will have a 90% chance of finding a 25-percentage point change over time to be statistically significant.  A sample size of approximately 250 households results in a MDE of 15% at power of 90%. At any one point in time, a sample size of 100 will result in less than a 12% margin of error at the target area level and a sample size of 250 will result in less than 7% margin of error.  The MDE and/or power will decrease as sample size decreases. 

Cluster Sampling Steps
Population Number
 Determine the total population across the area of interest (i.e., sum of all communities associated with the district or management area where you are working).
Divide the Population into Clusters
Clusters should contain households that are expected to be like one another (i.e., community or village)
Calculate cluster sample size
Aim to collect at least 100 complete responses across all clusters. We will call this number S. The 100 surveys should be divided proportionally among the villages.
Village household sample size: C = S*(# village population/total population)
If an area of interest contains less than 100 households, survey all households.
Select households within cluster
If appropriate, divide clusters into sub-clusters (i.e., neighborhood).
If population size by neighborhood is known, repeat # 3 to assign a sample size to each sub-cluster. 
If population size by neighborhood is not known, divide the cluster sample size equally among sub-clusters. 
Select every nth household within a cluster or sub-cluster.  Calculate n by dividing the estimated total number of households by the sample size. For instance, if you expect 100 households and you need to sample 20 you would sample every 5th household. 
If respondents are not available in the selected household, move to the next household. 

Respondent Selection
A critical goal of the household survey is to obtain information that is representative of the entire household from both men and women. The following best practices are recommended for obtaining survey responses that accurately represent the entire household and ensure equal inclusion of both men and women as the primary respondents.

Gender stratification:
Use a random number generator (e.g. Microsoft Excel RAND function or www.numbergenerator.org) to assign half of the households to a male respondent and half to a female respondent.
If you are selecting every 5th house with a total sample size of 20, randomly assign 10 as a female respondent and 10 as a male respondent.  An example could be assigning female respondent to household number 1, 3, 6, 7, 8, 13, 15, 18, 9, 10 and male respondent to household number 2, 4, 5, 11, 12, 14, 16, 17, 19, 20. 
Select a time of day for the survey when you believe either the respondent will be available (this is particularly important for ensuring a representative sample of female respondents).
Choose a respondent in the household  that is capable of providing accurate answers for the entire household. If the primary respondent is unsure or unable to confidently address the questions for the entire household, consider consulting other individuals present in the household.

Within household respondent selection
Determine who from the household roster is eligible to respond, based on their gender (only women from a household assigned to “female” and men from a household assigned to “male”) and age (over 18). 
Select the household member with the nearest birthday. 
